version: '3'
services:
  strapi:
    restart: always
    build: .
    volumes:
      - ./app/config:/app/config
      - ./app/database:/app/database
      - ./app/public:/app/public
      - ./app/src:/app/src
    ports:
      - '1337:1337'
# volumes:
#   node_modules:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./runtime/node_modules