version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: 
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi-prod
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: 
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'